// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quvudbfraknbuxojozbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1dnVkYmZyYWtuYnV4b2pvemJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExODU3MTUsImV4cCI6MjA1Njc2MTcxNX0.uKHHJcZ-TVwY0mARukW7n9nmnTbpB0pmlNLiJ5zMdGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);